### ISSUE TITLE
Gifting causes non-null violation in DB

### ISSUE THREAD

**Issue by siruguri** [JoyFoodly/joyful_12#10]

**Comment by whatasunnyday** [comment]
So this issue is temporarily resolved by https://github.com/JoyFoodly/joyful_12/commit/f3d83d218fa26195df02a61463d76d887238af50. I'm a bit confused about what's going on and I was hoping you might be able to try something @siruguri. I think the database is not in sync with db/schema.rb and the migrations. I know that you were able to replicate the issue locally but I have not been able to. Can you try dropping the db and restarting it using something like `rake db:setup` and not adding this patch? I'm curious if 0167afa will fix it for you.

**Comment by siruguri** [comment]
Okay, will do.

**Comment by whatasunnyday** [comment]
@siruguri Should we close this issue if we're sticking with the hack?

**Comment by siruguri** [comment]
f3d83d2.

using a hack - payments without users have user_id = -1
